name: rosci
on:
  pull_request:
    paths-ignore: 
      - '*.md'
      - '*LICENSE'
  push:
    branches: [rolling]
    paths-ignore:
      - '*.md'
  workflow_dispatch:
jobs:
  build_and_test:
    name: rosci_${{ matrix.ros-distro }}
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.ros-distro }}-ros-base
    strategy:
      fail-fast: false
      matrix:
        ros-distro: ["${{ github.base_ref || github.ref_name }}", jazzy]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Setup ros
        uses: ros-tooling/setup-ros@v0.7
      - 
        name: build and test using rosci
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ matrix.ros-distro }}